pipelineName: marvin-{{cookiecutter.project_name}}
description: Apache Marvin-AI DASFE pipeline

defaultParams:
    storageBucket: marvin-pipelines
    setupCommand: pip install -r requirements.txt
    envVars:
        - PIPELINE_NAME: marvin-{{cookiecutter.project_name}}
    dependencies:
        - meta.dt
    globalFiles:
        - requirements.txt
    envFile:
        .env

pipelineSteps:
    - name: acquisitor
      description: Acquisitor
      entrypoint: python3 runner.py --action Acquisitor
      envVars:
        - MY_ENV_VAR: test_specific_env
      fileInputs:
      fileOutputs:

    - name: tpreparator
      description: Training preparator
      runAfter: acquisitor
      entrypoint: python3 runner.py --action TPreparator
      fileInputs:
      fileOutputs:

    - name: trainer
      description: Trainer
      runAfter: tpreparator
      entrypoint: python3 runner.py --action Trainer
      fileInputs:
      fileOutputs:

    - name: evaluator
      description: Evaluator
      runAfter: trainer
      entrypoint: python3 runner.py --action Evaluator
      fileInputs:
      fileOutputs: