pipelineName: pipeline_housing_prices

defaultParams:
    storageBucket: housing_prices
    setupCommand: "pip install -r requirements.txt"
    envVars:
        - S3_ACCESS_KEY: minio_key
        - S3_SECRET_KEY: minio_secret
        - S3_ENDPOINT: minio_uri
    dependencies:
        - requirements.txt
        - test.csv
        - train.csv
        - acquisitor.py
        - data_prep.py
        - train_model.py
        - evaluate.py

pipeline:
    - stepName: acquisitor
      description: Acquisitor
      entrypoint: acquisitor.py
      command: "python acquisitor.py"
      inputs:
        - test.csv
        - train.csv

    - stepName: data_prep
      description: Data preparator
      runAfter:
        - acquisitor
      entrypoint: data_prep.py
      command: "python data_prep.py"
      inputs:
        - test.csv
        - train.csv
      outputs:
        - X_train.csv
        - y_train.csv
        - X_test.csv
        - y_test.csv

    - stepName: train_model
      description: Train the machine learning model
      runAfter:
        - data_prep
      entrypoint: "python train_model.py"
      inputs:
        - X_train.csv
        - y_train.csv
        - X_test.csv
        - y_test.csv
      outputs:
        - regressionTree
        - regressionLinear
        - randomForest

    - stepName: evaluate
      description: Evaluates the metrics
      runAfter:
        - train_model
      entrypoint: evaluate.py
      command: "python evaluate.py"
      inputs:
        - X_train.csv
        - y_train.csv
        - X_test.csv
        - y_test.csv
        - regressionTree
        - regressionLinear
        - randomForest
