pipelineName: pipeline_housing_prices
description: Pipeline for presentation of famous housing_prices problem

defaultParams:
    storageBucket: housing_prices
    setupCommand: pip install -r requirements.txt
    envVars:
        - S3_ACCESS_KEY: minio_key
        - S3_SECRET_KEY: minio_secret
        - S3_ENDPOINT: minio_uri
    dependencies:
        - requirements.txt
        - test.csv
        - train.csv
        - acquisitor.py
        - data_prep.py
        - train_model.py
        - evaluate.py

pipelineSteps:
    - name: acquisitor
      description: Acquisitor
      entrypoint: python acquisitor.py
      ennVars:
        - MY_ENV_VAR: test_specific_env
      fileInputs:
        - test.csv
        - train.csv

    - name: data_prep
      description: Data preparator
      runAfter:
        - acquisitor
      entrypoint: python data_prep.py
      fileInputs:
        - test.csv
        - train.csv
      fileOutputs:
        - X_train.csv
        - y_train.csv
        - X_test.csv
        - y_test.csv

    - name: train_model
      description: Train the machine learning model
      runAfter:
        - data_prep
      entrypoint: python train_model.py
      fileInputs:
        - X_train.csv
        - y_train.csv
        - X_test.csv
        - y_test.csv
      fileOutputs:
        - regressionTree
        - regressionLinear
        - randomForest

    - name: evaluate
      description: Evaluates the metrics
      runAfter:
        - train_model
      entrypoint: python evaluate.py
      fileInputs:
        - X_train.csv
        - y_train.csv
        - X_test.csv
        - y_test.csv
        - regressionTree
        - regressionLinear
        - randomForest
